---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2025/6/9 上午11:25
---

--1.参数列表
--1.1.优惠劵id
local voucherId=ARGV[1]
--1.2. 用户id
local userId=ARGV[2]
--1.3订单id
local orderId=ARGV[3]

--2.数据key
local stockKey= 'seckill:stock:' .. voucherId
local orderKey= 'seckill:order:' .. voucherId

--3.脚本业务
--3.1判断库存是否充足
if(tonumber( redis.call('get',stockKey)) <= 0) then
    --库存不足
    return 1
end
--判断用户是否下单 SISMEMBER
if(redis.call('sismember',orderKey,userId) == 1) then
    --存在，说明重复下单
    return 2
end
--扣除库存
redis.call('incrby',stockKey,-1)
--下单（保存用户）
redis.call('sadd',orderKey,userId)
--发送消息到队列
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0